// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { jsonStorage } from '@/lib/jsonStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Toggle between Supabase and JSON storage
const USE_JSON_STORAGE = !SUPABASE_URL || SUPABASE_URL === 'USE_JSON_STORAGE';

export const supabase = USE_JSON_STORAGE 
  ? (jsonStorage as any)
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });

// Export helper to check which storage is being used
export const isUsingJSONStorage = () => USE_JSON_STORAGE;